config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  resources :questions do
    member do
      put "hide"
    end
  end

  resource :session, only: %i[new create destroy update]

  resources :users, except: [:index], param: :nickname

  resources :tags, only: [:show], param: :name

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  belongs_to :user
  belongs_to :author, class_name: "User", optional: true

  validates :body, presence: true, length: { maximum: 280 }

  after_save_commit :set_tags

  def set_tags
    self.tags =
      "#{body} #{answer}".downcase.scan(Tag::REGEX).uniq.map do |hashtag|
        Tag.create_or_find_by(name: hashtag.downcase.delete("#"))
      end
  end
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  REGEX = (/#[\p{L}\d_]+/).freeze

  has_many :question_tags, dependent: :destroy
  has_many :questions, through: :question_tags

  scope :with_questions, -> { where_exists(:question_tags) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy

  has_secure_password

  before_validation :downcase_nickname, :downcase_email

  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w\.-]+@[A-Za-z\d\-\.+]+\.[a-z]+\z/}
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: /\A\w+\z/}
  validates :color, format: { with: /\A#[a-f\d]{6}\z/}

  private

  def downcase_nickname
    nickname.downcase!
  end

  def downcase_email
    nickname.downcase!
  end

  def to_param
    nickname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: "Вам сюда нельзя!"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update edit hide]
  before_action :set_question_for_current_user, only: %i[update edit hide]

  def create
    question_params = params.require(:question).permit(:body, :user_id)
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user.nickname), notice: "Вы создали новый вопрос!"
    else
      flash.now[:alert] = "Вы неправильно заполнили поля формы вопроса!"
      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)
    @question.update(question_params)

    redirect_to user_path(@question.user.nickname), notice: "Вы изменили вопрос!"
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to root_path, notice: "Вы удалили вопрос!"
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @question = Question.new
    @questions = Question.order("created_at DESC")
    @tags = Tag.with_questions
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def edit
  end

  def hide
    @question.update(hidden: true)

    redirect_to user_path(@question.user), notice: "Вы скрыли вопрос!"
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: "Вы вошли на сайт"
    else
      flash.now[:alert] = "Неправильный email или пароль"

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: "Вы вышли!"
  end

  def update
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.where_exists(:questions).find_by!(name: params[:name])
    @questions_with_tag = @tag.questions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: "Вы успешно зарегистрировались и вошли!"
    else
      flash.now[:alert] = "Вы неправильно заполнили поля формы регистрации!"

      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "Ваши данные обновлены!"
    else
      flash.now[:alert] = "При попытке сохранить измнения возникли ошибки."

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: "Пользователь удалён!"
  end

  def show
    @questions = @user.questions.order("created_at DESC")
    @question = Question.new(user: @user)
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, form1, form2, form3)
    return form3 if (count % 100).between?(11, 14)

    case count % 10
    when 1 then form1
    when 2..4 then form2
    else
      form3
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def render_with_hashtags(text)
    text.gsub(Tag::REGEX){ |htag| link_to htag, tag_path(htag.delete("#")) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def nickname_with_at(current_user)
    "@#{current_user.nickname}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <% if current_user.present? %>
        <div class="navbar" style="background-color: <%= current_user.color %>;">
      <% else %>
        <div class="navbar" style="background-color: #dfe0e2;">
      <% end %>
        <p class="title text-bold mr-sm">
          <%= link_to "Ask me!", root_path, class: "intro" %>
        </p>
        <div>
          <% if current_user.present? %>
            <%= link_to nickname_with_at(current_user), user_path(current_user.nickname), class: "mr-sm nickname" %>
            <%= button_to "Выйти", session_path, method: :delete, class: "button button-yellow mr-sm" %>
          <% else %>
            <%= link_to "Регистрация", new_user_path, class: "button button-yellow mr-sm" %>
            <%= link_to "Вход", new_session_path, class: "button button-yellow mr-sm" %>
          <% end %>
        </div>
      </div>
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice text-center"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert text-center"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question, data: {turbo: false} do |form| %>
  <%= form.hidden_field :user_id %>
  <p><%= form.label :body, "Текст вопроса" %></p>
  <p><%= form.text_area :body, rows: 5, class: "form-text-area" %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, "Ответ" %></p>
    <p><%= form.text_area :answer, rows: 5, class: "form-text-area" %></p>
  <% end %>

  <p class="mt">
    <%= form.submit "Сохранить", class: "button button-main" %>
    или
    <%=  link_to "Вернуться", :back %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm text-with-line-breaks">
  <%= sanitize render_with_hashtags(question.body) %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm text-red text-bold">
    <%= sanitize render_with_hashtags(question.answer) %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-gray">
    <p>
      <%= l(question.created_at, format: :short) %>
      Вопрос задал
      <% if question.author.nil? %>
        Аноним
      <% else %>
        <%= link_to nickname_with_at(question.author), user_path(question.author.nickname), class: "mr-sm nickname" %>
      <% end %>
    </p>
  </div>

  <% if current_user == question.user %>
    <div class="icon">
      <% if question.answer.present? %>
        <%= link_to fa_icon("edit"), edit_question_path(question), title: "Изменить вопрос" %>
      <% else %>
        <%= link_to fa_icon("reply"), edit_question_path(question), title: "Ответить на вопрос" %>
      <% end %>

      <%= button_to fa_icon("trash-o"), question_path(question), method: :delete, title: "Удалить вопрос", data: { turbo_confirm: "Вы уверены, что хотите удалить вопрос?" } %>

      <% unless question.hidden? %>
        <%= button_to fa_icon("low-vision"), hide_question_path(question), method: :put, title: "Сделать скрытым", data: { turbo_confirm: "Вы уверены, что хотите скрыть вопрос?" } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <%= render "form", question: @question %>
</div>

app/views/questions/hashtags.html.erb
<div>
  <h2 class="title-lg mb container-question text-center">
    <%= @questions.count %>
    <%= inclination(@questions.count, "вопрос", "вопроса", "вопросов") %>
  </h2>

  <% @questions.each do |question| %>
    <% if question.hidden? %>
      <div class="container-question mb-sm hide">
        <%= render question %>
      </div>
    <% else %>
      <div class="container-question mb-sm">
        <%= render question %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/questions/index.html.erb
<div>
  <h2 class="title-lg mb container-question text-center">
    <%= @questions.count %>
    <%= inclination(@questions.count, "вопрос", "вопроса", "вопросов") %>
  </h2>
  <div class="title-lg container-question text-center">
    <h2>Все хэштеги</h2>
    <p>
      <% @tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag.name) %>
      <% end %>
    </p>
</div>
  <% @questions.each do |question| %>
    <% if question.hidden? %>
      <div class="container-question mb-sm hide">
        <%= render question %>
      </div>
    <% else %>
      <div class="container-question mb-sm">
        <%= render question %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Новый вопрос</h2>
  <p class="mb">для <%= link_to "@#{@question.user.nickname}", user_path(@question.user.nickname) %></p>
  <% if @question.errors.any? %>
    <div class="mt">
      <% @question.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= render "form", question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>

  <%= render @question %>

  <p class="mt"><%= link_to "Все вопросы", questions_path %></p>
</div>

app/views/tags/show.html.erb
<div>
  <h2 class="title-lg mb container-question text-center">
    <%= @questions_with_tag.count %>
    <%= inclination(@questions_with_tag.count, "вопрос ", "вопроса", "вопросов") %>
    c тэгом <%= link_to @tag.name, tag_path(@tag.name) %>
  </h2>

  <% @questions_with_tag.each do |question| %>
    <% if question.hidden? %>
      <div class="container-question mb-sm hide">
        <%= render question %>
      </div>
    <% else %>
      <div class="container-question mb-sm">
        <%= render question %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_questions_or_ghost.html.erb
<% if @questions.count == 0 %>
    <h2 class="title mb container-question text-center">Упс, похоже здесь ещё нет вопросов! Будьте первым!</h2>
    <div class="text-center empty">
      <img src="https://i.gifer.com/yH.gif" alt="[ghost]">
    </div>

  <% else %>
    <h2 class="title-lg mb container-question text-center">
      <%= @questions.count %>
      <%= inclination(@questions.count, "вопрос", "вопроса", "вопросов") %>
    </h2>

    <% @questions.each do |question| %>
      <% if question.hidden? %>
        <div class="container-question mb-sm hide">
          <%= render question %>
        </div>
      <% else %>
        <div class="container-question mb-sm">
          <%= render question %>
        </div>
      <% end %>
    <% end %>
  <% end %>

app/views/users/edit.html.erb
<div class="container text-center">
  <h2 class="title">Изменения данных аккаунта.</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, url: user_path(@user.nickname), data: {turbo: false} do |form| %>
      <p><%= form.label :name, "Ваше имя" %></p>
      <p><%= form.text_field :name, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :nickname, "Ник на сайте" %></p>
      <p><%= form.text_field :nickname, class: "form-text-field" %></p>

      <p class="mt-lg text-sm">Если не хотите менять пароль - оставьте эти поля пустыми</p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :header_background_color %></p>
      <p><%= form.color_field :color, class: "form-color-field mt" %></p>

      <p class="mt-lg mb-lg">
        <%= form.submit "Сохранить", class: "button button-main mt-lg " %>
        <span class="text-sm">или <%= link_to "Вернуться", :back, class: "text-red" %></span>
      </p>
    <% end %>

    <div class="mt-lg">
      <%= button_to "Удалить аккаунт", user_path(@user.nickname),
        method: :delete,
        form: {data: {turbo_confirm: "Вы точно хотите удалить свой профиль?"}},
        class: "text-red text-sm" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container text-center">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, "Ваше имя" %></p>
      <p><%= form.text_field :name, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :nickname, "Ник на сайте" %></p>
      <p><%= form.text_field :nickname, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: "form-text-field" %></p>

      <p><%= form.submit "Зарегистрироваться", class: "button button-main mt-lg" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box mt-lg">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <% if current_user == @user %>
    <p class="mt mb">
      <%= link_to fa_icon("pencil"), edit_user_path(@user.nickname) %>
    </p>
  <% end %>

  <p class="text-bold mt mb-lg"><%= nickname_with_at(@user) %></p>
</div>

<div class="container">
  <%= link_to "Спроси меня", new_question_path(user_id: @user.id), class: "button button-yellow" %>

  <p class="mt text-center mb">
    <%= render "questions/form", question: @question %>
  </p>
</div>

<div>
  <%= render "questions_or_ghost" %>
</div>